import type { Metadata } from "next";
import { Gravitas_One } from "next/font/google";
import "./globals.css";

const gravitasOne = Gravitas_One({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kailua - Maui Brewing Co.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="d-flex flex-column min-vh-100">
        {children}
      </body>
    </html>
  );
}